// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/gosh/entity/RecTagColdFeature.proto

package com.gosh.entity;

public final class RecTagColdFeature {
  private RecTagColdFeature() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PostItemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.gosh.entity.PostItem)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 post_id = 1;</code>
     * @return The postId.
     */
    long getPostId();

    /**
     * <code>float score = 2;</code>
     * @return The score.
     */
    float getScore();
  }
  /**
   * Protobuf type {@code com.gosh.entity.PostItem}
   */
  public static final class PostItem extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.gosh.entity.PostItem)
      PostItemOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PostItem.newBuilder() to construct.
    private PostItem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PostItem() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PostItem();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PostItem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              postId_ = input.readInt64();
              break;
            }
            case 21: {

              score_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gosh.entity.RecTagColdFeature.internal_static_com_gosh_entity_PostItem_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gosh.entity.RecTagColdFeature.internal_static_com_gosh_entity_PostItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gosh.entity.RecTagColdFeature.PostItem.class, com.gosh.entity.RecTagColdFeature.PostItem.Builder.class);
    }

    public static final int POST_ID_FIELD_NUMBER = 1;
    private long postId_;
    /**
     * <code>int64 post_id = 1;</code>
     * @return The postId.
     */
    @java.lang.Override
    public long getPostId() {
      return postId_;
    }

    public static final int SCORE_FIELD_NUMBER = 2;
    private float score_;
    /**
     * <code>float score = 2;</code>
     * @return The score.
     */
    @java.lang.Override
    public float getScore() {
      return score_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (postId_ != 0L) {
        output.writeInt64(1, postId_);
      }
      if (java.lang.Float.floatToRawIntBits(score_) != 0) {
        output.writeFloat(2, score_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (postId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, postId_);
      }
      if (java.lang.Float.floatToRawIntBits(score_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, score_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gosh.entity.RecTagColdFeature.PostItem)) {
        return super.equals(obj);
      }
      com.gosh.entity.RecTagColdFeature.PostItem other = (com.gosh.entity.RecTagColdFeature.PostItem) obj;

      if (getPostId()
          != other.getPostId()) return false;
      if (java.lang.Float.floatToIntBits(getScore())
          != java.lang.Float.floatToIntBits(
              other.getScore())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + POST_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPostId());
      hash = (37 * hash) + SCORE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getScore());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gosh.entity.RecTagColdFeature.PostItem parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gosh.entity.RecTagColdFeature.PostItem parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gosh.entity.RecTagColdFeature.PostItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gosh.entity.RecTagColdFeature.PostItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gosh.entity.RecTagColdFeature.PostItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gosh.entity.RecTagColdFeature.PostItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gosh.entity.RecTagColdFeature.PostItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gosh.entity.RecTagColdFeature.PostItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gosh.entity.RecTagColdFeature.PostItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.gosh.entity.RecTagColdFeature.PostItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gosh.entity.RecTagColdFeature.PostItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gosh.entity.RecTagColdFeature.PostItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gosh.entity.RecTagColdFeature.PostItem prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.gosh.entity.PostItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.gosh.entity.PostItem)
        com.gosh.entity.RecTagColdFeature.PostItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gosh.entity.RecTagColdFeature.internal_static_com_gosh_entity_PostItem_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gosh.entity.RecTagColdFeature.internal_static_com_gosh_entity_PostItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gosh.entity.RecTagColdFeature.PostItem.class, com.gosh.entity.RecTagColdFeature.PostItem.Builder.class);
      }

      // Construct using com.gosh.entity.RecTagColdFeature.PostItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        postId_ = 0L;

        score_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gosh.entity.RecTagColdFeature.internal_static_com_gosh_entity_PostItem_descriptor;
      }

      @java.lang.Override
      public com.gosh.entity.RecTagColdFeature.PostItem getDefaultInstanceForType() {
        return com.gosh.entity.RecTagColdFeature.PostItem.getDefaultInstance();
      }

      @java.lang.Override
      public com.gosh.entity.RecTagColdFeature.PostItem build() {
        com.gosh.entity.RecTagColdFeature.PostItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.gosh.entity.RecTagColdFeature.PostItem buildPartial() {
        com.gosh.entity.RecTagColdFeature.PostItem result = new com.gosh.entity.RecTagColdFeature.PostItem(this);
        result.postId_ = postId_;
        result.score_ = score_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gosh.entity.RecTagColdFeature.PostItem) {
          return mergeFrom((com.gosh.entity.RecTagColdFeature.PostItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gosh.entity.RecTagColdFeature.PostItem other) {
        if (other == com.gosh.entity.RecTagColdFeature.PostItem.getDefaultInstance()) return this;
        if (other.getPostId() != 0L) {
          setPostId(other.getPostId());
        }
        if (other.getScore() != 0F) {
          setScore(other.getScore());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gosh.entity.RecTagColdFeature.PostItem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gosh.entity.RecTagColdFeature.PostItem) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long postId_ ;
      /**
       * <code>int64 post_id = 1;</code>
       * @return The postId.
       */
      @java.lang.Override
      public long getPostId() {
        return postId_;
      }
      /**
       * <code>int64 post_id = 1;</code>
       * @param value The postId to set.
       * @return This builder for chaining.
       */
      public Builder setPostId(long value) {
        
        postId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 post_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPostId() {
        
        postId_ = 0L;
        onChanged();
        return this;
      }

      private float score_ ;
      /**
       * <code>float score = 2;</code>
       * @return The score.
       */
      @java.lang.Override
      public float getScore() {
        return score_;
      }
      /**
       * <code>float score = 2;</code>
       * @param value The score to set.
       * @return This builder for chaining.
       */
      public Builder setScore(float value) {
        
        score_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float score = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearScore() {
        
        score_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.gosh.entity.PostItem)
    }

    // @@protoc_insertion_point(class_scope:com.gosh.entity.PostItem)
    private static final com.gosh.entity.RecTagColdFeature.PostItem DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gosh.entity.RecTagColdFeature.PostItem();
    }

    public static com.gosh.entity.RecTagColdFeature.PostItem getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PostItem>
        PARSER = new com.google.protobuf.AbstractParser<PostItem>() {
      @java.lang.Override
      public PostItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PostItem(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PostItem> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PostItem> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.gosh.entity.RecTagColdFeature.PostItem getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PostItemListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.gosh.entity.PostItemList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.gosh.entity.PostItem items = 1;</code>
     */
    java.util.List<com.gosh.entity.RecTagColdFeature.PostItem> 
        getItemsList();
    /**
     * <code>repeated .com.gosh.entity.PostItem items = 1;</code>
     */
    com.gosh.entity.RecTagColdFeature.PostItem getItems(int index);
    /**
     * <code>repeated .com.gosh.entity.PostItem items = 1;</code>
     */
    int getItemsCount();
    /**
     * <code>repeated .com.gosh.entity.PostItem items = 1;</code>
     */
    java.util.List<? extends com.gosh.entity.RecTagColdFeature.PostItemOrBuilder> 
        getItemsOrBuilderList();
    /**
     * <code>repeated .com.gosh.entity.PostItem items = 1;</code>
     */
    com.gosh.entity.RecTagColdFeature.PostItemOrBuilder getItemsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.gosh.entity.PostItemList}
   */
  public static final class PostItemList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.gosh.entity.PostItemList)
      PostItemListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PostItemList.newBuilder() to construct.
    private PostItemList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PostItemList() {
      items_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PostItemList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PostItemList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                items_ = new java.util.ArrayList<com.gosh.entity.RecTagColdFeature.PostItem>();
                mutable_bitField0_ |= 0x00000001;
              }
              items_.add(
                  input.readMessage(com.gosh.entity.RecTagColdFeature.PostItem.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          items_ = java.util.Collections.unmodifiableList(items_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gosh.entity.RecTagColdFeature.internal_static_com_gosh_entity_PostItemList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gosh.entity.RecTagColdFeature.internal_static_com_gosh_entity_PostItemList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gosh.entity.RecTagColdFeature.PostItemList.class, com.gosh.entity.RecTagColdFeature.PostItemList.Builder.class);
    }

    public static final int ITEMS_FIELD_NUMBER = 1;
    private java.util.List<com.gosh.entity.RecTagColdFeature.PostItem> items_;
    /**
     * <code>repeated .com.gosh.entity.PostItem items = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.gosh.entity.RecTagColdFeature.PostItem> getItemsList() {
      return items_;
    }
    /**
     * <code>repeated .com.gosh.entity.PostItem items = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.gosh.entity.RecTagColdFeature.PostItemOrBuilder> 
        getItemsOrBuilderList() {
      return items_;
    }
    /**
     * <code>repeated .com.gosh.entity.PostItem items = 1;</code>
     */
    @java.lang.Override
    public int getItemsCount() {
      return items_.size();
    }
    /**
     * <code>repeated .com.gosh.entity.PostItem items = 1;</code>
     */
    @java.lang.Override
    public com.gosh.entity.RecTagColdFeature.PostItem getItems(int index) {
      return items_.get(index);
    }
    /**
     * <code>repeated .com.gosh.entity.PostItem items = 1;</code>
     */
    @java.lang.Override
    public com.gosh.entity.RecTagColdFeature.PostItemOrBuilder getItemsOrBuilder(
        int index) {
      return items_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < items_.size(); i++) {
        output.writeMessage(1, items_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < items_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, items_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gosh.entity.RecTagColdFeature.PostItemList)) {
        return super.equals(obj);
      }
      com.gosh.entity.RecTagColdFeature.PostItemList other = (com.gosh.entity.RecTagColdFeature.PostItemList) obj;

      if (!getItemsList()
          .equals(other.getItemsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getItemsCount() > 0) {
        hash = (37 * hash) + ITEMS_FIELD_NUMBER;
        hash = (53 * hash) + getItemsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gosh.entity.RecTagColdFeature.PostItemList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gosh.entity.RecTagColdFeature.PostItemList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gosh.entity.RecTagColdFeature.PostItemList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gosh.entity.RecTagColdFeature.PostItemList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gosh.entity.RecTagColdFeature.PostItemList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gosh.entity.RecTagColdFeature.PostItemList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gosh.entity.RecTagColdFeature.PostItemList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gosh.entity.RecTagColdFeature.PostItemList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gosh.entity.RecTagColdFeature.PostItemList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.gosh.entity.RecTagColdFeature.PostItemList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gosh.entity.RecTagColdFeature.PostItemList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gosh.entity.RecTagColdFeature.PostItemList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gosh.entity.RecTagColdFeature.PostItemList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.gosh.entity.PostItemList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.gosh.entity.PostItemList)
        com.gosh.entity.RecTagColdFeature.PostItemListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gosh.entity.RecTagColdFeature.internal_static_com_gosh_entity_PostItemList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gosh.entity.RecTagColdFeature.internal_static_com_gosh_entity_PostItemList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gosh.entity.RecTagColdFeature.PostItemList.class, com.gosh.entity.RecTagColdFeature.PostItemList.Builder.class);
      }

      // Construct using com.gosh.entity.RecTagColdFeature.PostItemList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getItemsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gosh.entity.RecTagColdFeature.internal_static_com_gosh_entity_PostItemList_descriptor;
      }

      @java.lang.Override
      public com.gosh.entity.RecTagColdFeature.PostItemList getDefaultInstanceForType() {
        return com.gosh.entity.RecTagColdFeature.PostItemList.getDefaultInstance();
      }

      @java.lang.Override
      public com.gosh.entity.RecTagColdFeature.PostItemList build() {
        com.gosh.entity.RecTagColdFeature.PostItemList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.gosh.entity.RecTagColdFeature.PostItemList buildPartial() {
        com.gosh.entity.RecTagColdFeature.PostItemList result = new com.gosh.entity.RecTagColdFeature.PostItemList(this);
        int from_bitField0_ = bitField0_;
        if (itemsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            items_ = java.util.Collections.unmodifiableList(items_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.items_ = items_;
        } else {
          result.items_ = itemsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gosh.entity.RecTagColdFeature.PostItemList) {
          return mergeFrom((com.gosh.entity.RecTagColdFeature.PostItemList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gosh.entity.RecTagColdFeature.PostItemList other) {
        if (other == com.gosh.entity.RecTagColdFeature.PostItemList.getDefaultInstance()) return this;
        if (itemsBuilder_ == null) {
          if (!other.items_.isEmpty()) {
            if (items_.isEmpty()) {
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureItemsIsMutable();
              items_.addAll(other.items_);
            }
            onChanged();
          }
        } else {
          if (!other.items_.isEmpty()) {
            if (itemsBuilder_.isEmpty()) {
              itemsBuilder_.dispose();
              itemsBuilder_ = null;
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
              itemsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getItemsFieldBuilder() : null;
            } else {
              itemsBuilder_.addAllMessages(other.items_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gosh.entity.RecTagColdFeature.PostItemList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gosh.entity.RecTagColdFeature.PostItemList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.gosh.entity.RecTagColdFeature.PostItem> items_ =
        java.util.Collections.emptyList();
      private void ensureItemsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          items_ = new java.util.ArrayList<com.gosh.entity.RecTagColdFeature.PostItem>(items_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.gosh.entity.RecTagColdFeature.PostItem, com.gosh.entity.RecTagColdFeature.PostItem.Builder, com.gosh.entity.RecTagColdFeature.PostItemOrBuilder> itemsBuilder_;

      /**
       * <code>repeated .com.gosh.entity.PostItem items = 1;</code>
       */
      public java.util.List<com.gosh.entity.RecTagColdFeature.PostItem> getItemsList() {
        if (itemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(items_);
        } else {
          return itemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.gosh.entity.PostItem items = 1;</code>
       */
      public int getItemsCount() {
        if (itemsBuilder_ == null) {
          return items_.size();
        } else {
          return itemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.gosh.entity.PostItem items = 1;</code>
       */
      public com.gosh.entity.RecTagColdFeature.PostItem getItems(int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);
        } else {
          return itemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.gosh.entity.PostItem items = 1;</code>
       */
      public Builder setItems(
          int index, com.gosh.entity.RecTagColdFeature.PostItem value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.set(index, value);
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.gosh.entity.PostItem items = 1;</code>
       */
      public Builder setItems(
          int index, com.gosh.entity.RecTagColdFeature.PostItem.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.gosh.entity.PostItem items = 1;</code>
       */
      public Builder addItems(com.gosh.entity.RecTagColdFeature.PostItem value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.gosh.entity.PostItem items = 1;</code>
       */
      public Builder addItems(
          int index, com.gosh.entity.RecTagColdFeature.PostItem value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(index, value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.gosh.entity.PostItem items = 1;</code>
       */
      public Builder addItems(
          com.gosh.entity.RecTagColdFeature.PostItem.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.gosh.entity.PostItem items = 1;</code>
       */
      public Builder addItems(
          int index, com.gosh.entity.RecTagColdFeature.PostItem.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.gosh.entity.PostItem items = 1;</code>
       */
      public Builder addAllItems(
          java.lang.Iterable<? extends com.gosh.entity.RecTagColdFeature.PostItem> values) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, items_);
          onChanged();
        } else {
          itemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.gosh.entity.PostItem items = 1;</code>
       */
      public Builder clearItems() {
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.gosh.entity.PostItem items = 1;</code>
       */
      public Builder removeItems(int index) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.remove(index);
          onChanged();
        } else {
          itemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.gosh.entity.PostItem items = 1;</code>
       */
      public com.gosh.entity.RecTagColdFeature.PostItem.Builder getItemsBuilder(
          int index) {
        return getItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.gosh.entity.PostItem items = 1;</code>
       */
      public com.gosh.entity.RecTagColdFeature.PostItemOrBuilder getItemsOrBuilder(
          int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);  } else {
          return itemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.gosh.entity.PostItem items = 1;</code>
       */
      public java.util.List<? extends com.gosh.entity.RecTagColdFeature.PostItemOrBuilder> 
           getItemsOrBuilderList() {
        if (itemsBuilder_ != null) {
          return itemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(items_);
        }
      }
      /**
       * <code>repeated .com.gosh.entity.PostItem items = 1;</code>
       */
      public com.gosh.entity.RecTagColdFeature.PostItem.Builder addItemsBuilder() {
        return getItemsFieldBuilder().addBuilder(
            com.gosh.entity.RecTagColdFeature.PostItem.getDefaultInstance());
      }
      /**
       * <code>repeated .com.gosh.entity.PostItem items = 1;</code>
       */
      public com.gosh.entity.RecTagColdFeature.PostItem.Builder addItemsBuilder(
          int index) {
        return getItemsFieldBuilder().addBuilder(
            index, com.gosh.entity.RecTagColdFeature.PostItem.getDefaultInstance());
      }
      /**
       * <code>repeated .com.gosh.entity.PostItem items = 1;</code>
       */
      public java.util.List<com.gosh.entity.RecTagColdFeature.PostItem.Builder> 
           getItemsBuilderList() {
        return getItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.gosh.entity.RecTagColdFeature.PostItem, com.gosh.entity.RecTagColdFeature.PostItem.Builder, com.gosh.entity.RecTagColdFeature.PostItemOrBuilder> 
          getItemsFieldBuilder() {
        if (itemsBuilder_ == null) {
          itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.gosh.entity.RecTagColdFeature.PostItem, com.gosh.entity.RecTagColdFeature.PostItem.Builder, com.gosh.entity.RecTagColdFeature.PostItemOrBuilder>(
                  items_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          items_ = null;
        }
        return itemsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.gosh.entity.PostItemList)
    }

    // @@protoc_insertion_point(class_scope:com.gosh.entity.PostItemList)
    private static final com.gosh.entity.RecTagColdFeature.PostItemList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gosh.entity.RecTagColdFeature.PostItemList();
    }

    public static com.gosh.entity.RecTagColdFeature.PostItemList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PostItemList>
        PARSER = new com.google.protobuf.AbstractParser<PostItemList>() {
      @java.lang.Override
      public PostItemList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PostItemList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PostItemList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PostItemList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.gosh.entity.RecTagColdFeature.PostItemList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PostTagColdFeatureOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.gosh.entity.PostTagColdFeature)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string tag = 1;</code>
     * @return The tag.
     */
    java.lang.String getTag();
    /**
     * <code>string tag = 1;</code>
     * @return The bytes for tag.
     */
    com.google.protobuf.ByteString
        getTagBytes();

    /**
     * <code>string tag_post_info_24h = 2;</code>
     * @return The tagPostInfo24h.
     */
    java.lang.String getTagPostInfo24H();
    /**
     * <code>string tag_post_info_24h = 2;</code>
     * @return The bytes for tagPostInfo24h.
     */
    com.google.protobuf.ByteString
        getTagPostInfo24HBytes();
  }
  /**
   * Protobuf type {@code com.gosh.entity.PostTagColdFeature}
   */
  public static final class PostTagColdFeature extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.gosh.entity.PostTagColdFeature)
      PostTagColdFeatureOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PostTagColdFeature.newBuilder() to construct.
    private PostTagColdFeature(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PostTagColdFeature() {
      tag_ = "";
      tagPostInfo24H_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PostTagColdFeature();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PostTagColdFeature(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              tag_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              tagPostInfo24H_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gosh.entity.RecTagColdFeature.internal_static_com_gosh_entity_PostTagColdFeature_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gosh.entity.RecTagColdFeature.internal_static_com_gosh_entity_PostTagColdFeature_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gosh.entity.RecTagColdFeature.PostTagColdFeature.class, com.gosh.entity.RecTagColdFeature.PostTagColdFeature.Builder.class);
    }

    public static final int TAG_FIELD_NUMBER = 1;
    private volatile java.lang.Object tag_;
    /**
     * <code>string tag = 1;</code>
     * @return The tag.
     */
    @java.lang.Override
    public java.lang.String getTag() {
      java.lang.Object ref = tag_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tag_ = s;
        return s;
      }
    }
    /**
     * <code>string tag = 1;</code>
     * @return The bytes for tag.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTagBytes() {
      java.lang.Object ref = tag_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tag_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TAG_POST_INFO_24H_FIELD_NUMBER = 2;
    private volatile java.lang.Object tagPostInfo24H_;
    /**
     * <code>string tag_post_info_24h = 2;</code>
     * @return The tagPostInfo24h.
     */
    @java.lang.Override
    public java.lang.String getTagPostInfo24H() {
      java.lang.Object ref = tagPostInfo24H_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tagPostInfo24H_ = s;
        return s;
      }
    }
    /**
     * <code>string tag_post_info_24h = 2;</code>
     * @return The bytes for tagPostInfo24h.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTagPostInfo24HBytes() {
      java.lang.Object ref = tagPostInfo24H_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tagPostInfo24H_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tag_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tag_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tagPostInfo24H_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, tagPostInfo24H_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tag_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, tag_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tagPostInfo24H_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, tagPostInfo24H_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gosh.entity.RecTagColdFeature.PostTagColdFeature)) {
        return super.equals(obj);
      }
      com.gosh.entity.RecTagColdFeature.PostTagColdFeature other = (com.gosh.entity.RecTagColdFeature.PostTagColdFeature) obj;

      if (!getTag()
          .equals(other.getTag())) return false;
      if (!getTagPostInfo24H()
          .equals(other.getTagPostInfo24H())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TAG_FIELD_NUMBER;
      hash = (53 * hash) + getTag().hashCode();
      hash = (37 * hash) + TAG_POST_INFO_24H_FIELD_NUMBER;
      hash = (53 * hash) + getTagPostInfo24H().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gosh.entity.RecTagColdFeature.PostTagColdFeature parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gosh.entity.RecTagColdFeature.PostTagColdFeature parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gosh.entity.RecTagColdFeature.PostTagColdFeature parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gosh.entity.RecTagColdFeature.PostTagColdFeature parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gosh.entity.RecTagColdFeature.PostTagColdFeature parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gosh.entity.RecTagColdFeature.PostTagColdFeature parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gosh.entity.RecTagColdFeature.PostTagColdFeature parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gosh.entity.RecTagColdFeature.PostTagColdFeature parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gosh.entity.RecTagColdFeature.PostTagColdFeature parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.gosh.entity.RecTagColdFeature.PostTagColdFeature parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gosh.entity.RecTagColdFeature.PostTagColdFeature parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gosh.entity.RecTagColdFeature.PostTagColdFeature parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gosh.entity.RecTagColdFeature.PostTagColdFeature prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.gosh.entity.PostTagColdFeature}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.gosh.entity.PostTagColdFeature)
        com.gosh.entity.RecTagColdFeature.PostTagColdFeatureOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gosh.entity.RecTagColdFeature.internal_static_com_gosh_entity_PostTagColdFeature_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gosh.entity.RecTagColdFeature.internal_static_com_gosh_entity_PostTagColdFeature_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gosh.entity.RecTagColdFeature.PostTagColdFeature.class, com.gosh.entity.RecTagColdFeature.PostTagColdFeature.Builder.class);
      }

      // Construct using com.gosh.entity.RecTagColdFeature.PostTagColdFeature.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        tag_ = "";

        tagPostInfo24H_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gosh.entity.RecTagColdFeature.internal_static_com_gosh_entity_PostTagColdFeature_descriptor;
      }

      @java.lang.Override
      public com.gosh.entity.RecTagColdFeature.PostTagColdFeature getDefaultInstanceForType() {
        return com.gosh.entity.RecTagColdFeature.PostTagColdFeature.getDefaultInstance();
      }

      @java.lang.Override
      public com.gosh.entity.RecTagColdFeature.PostTagColdFeature build() {
        com.gosh.entity.RecTagColdFeature.PostTagColdFeature result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.gosh.entity.RecTagColdFeature.PostTagColdFeature buildPartial() {
        com.gosh.entity.RecTagColdFeature.PostTagColdFeature result = new com.gosh.entity.RecTagColdFeature.PostTagColdFeature(this);
        result.tag_ = tag_;
        result.tagPostInfo24H_ = tagPostInfo24H_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gosh.entity.RecTagColdFeature.PostTagColdFeature) {
          return mergeFrom((com.gosh.entity.RecTagColdFeature.PostTagColdFeature)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gosh.entity.RecTagColdFeature.PostTagColdFeature other) {
        if (other == com.gosh.entity.RecTagColdFeature.PostTagColdFeature.getDefaultInstance()) return this;
        if (!other.getTag().isEmpty()) {
          tag_ = other.tag_;
          onChanged();
        }
        if (!other.getTagPostInfo24H().isEmpty()) {
          tagPostInfo24H_ = other.tagPostInfo24H_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gosh.entity.RecTagColdFeature.PostTagColdFeature parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gosh.entity.RecTagColdFeature.PostTagColdFeature) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object tag_ = "";
      /**
       * <code>string tag = 1;</code>
       * @return The tag.
       */
      public java.lang.String getTag() {
        java.lang.Object ref = tag_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tag_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string tag = 1;</code>
       * @return The bytes for tag.
       */
      public com.google.protobuf.ByteString
          getTagBytes() {
        java.lang.Object ref = tag_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tag_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tag = 1;</code>
       * @param value The tag to set.
       * @return This builder for chaining.
       */
      public Builder setTag(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string tag = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTag() {
        
        tag_ = getDefaultInstance().getTag();
        onChanged();
        return this;
      }
      /**
       * <code>string tag = 1;</code>
       * @param value The bytes for tag to set.
       * @return This builder for chaining.
       */
      public Builder setTagBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tag_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object tagPostInfo24H_ = "";
      /**
       * <code>string tag_post_info_24h = 2;</code>
       * @return The tagPostInfo24h.
       */
      public java.lang.String getTagPostInfo24H() {
        java.lang.Object ref = tagPostInfo24H_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tagPostInfo24H_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string tag_post_info_24h = 2;</code>
       * @return The bytes for tagPostInfo24h.
       */
      public com.google.protobuf.ByteString
          getTagPostInfo24HBytes() {
        java.lang.Object ref = tagPostInfo24H_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tagPostInfo24H_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tag_post_info_24h = 2;</code>
       * @param value The tagPostInfo24h to set.
       * @return This builder for chaining.
       */
      public Builder setTagPostInfo24H(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tagPostInfo24H_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string tag_post_info_24h = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTagPostInfo24H() {
        
        tagPostInfo24H_ = getDefaultInstance().getTagPostInfo24H();
        onChanged();
        return this;
      }
      /**
       * <code>string tag_post_info_24h = 2;</code>
       * @param value The bytes for tagPostInfo24h to set.
       * @return This builder for chaining.
       */
      public Builder setTagPostInfo24HBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tagPostInfo24H_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.gosh.entity.PostTagColdFeature)
    }

    // @@protoc_insertion_point(class_scope:com.gosh.entity.PostTagColdFeature)
    private static final com.gosh.entity.RecTagColdFeature.PostTagColdFeature DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gosh.entity.RecTagColdFeature.PostTagColdFeature();
    }

    public static com.gosh.entity.RecTagColdFeature.PostTagColdFeature getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PostTagColdFeature>
        PARSER = new com.google.protobuf.AbstractParser<PostTagColdFeature>() {
      @java.lang.Override
      public PostTagColdFeature parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PostTagColdFeature(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PostTagColdFeature> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PostTagColdFeature> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.gosh.entity.RecTagColdFeature.PostTagColdFeature getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gosh_entity_PostItem_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gosh_entity_PostItem_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gosh_entity_PostItemList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gosh_entity_PostItemList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gosh_entity_PostTagColdFeature_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gosh_entity_PostTagColdFeature_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'com/gosh/entity/RecTagColdFeature.prot" +
      "o\022\017com.gosh.entity\"*\n\010PostItem\022\017\n\007post_i" +
      "d\030\001 \001(\003\022\r\n\005score\030\002 \001(\002\"8\n\014PostItemList\022(" +
      "\n\005items\030\001 \003(\0132\031.com.gosh.entity.PostItem" +
      "\"<\n\022PostTagColdFeature\022\013\n\003tag\030\001 \001(\t\022\031\n\021t" +
      "ag_post_info_24h\030\002 \001(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_gosh_entity_PostItem_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_gosh_entity_PostItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gosh_entity_PostItem_descriptor,
        new java.lang.String[] { "PostId", "Score", });
    internal_static_com_gosh_entity_PostItemList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_gosh_entity_PostItemList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gosh_entity_PostItemList_descriptor,
        new java.lang.String[] { "Items", });
    internal_static_com_gosh_entity_PostTagColdFeature_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_gosh_entity_PostTagColdFeature_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gosh_entity_PostTagColdFeature_descriptor,
        new java.lang.String[] { "Tag", "TagPostInfo24H", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
